name: Windows Build

on: [push]

jobs:
  build-qt:
    name: Windows Qt Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
#      - run: scripts/build-qt-windows.ps1
#      - uses: actions/upload-artifact@v2
#        with:
#          name: QtStatic
#          path: QtStatic.zip
#        - uses: actions/checkout@v2
#          with:
#            repository: x42/libltc
#            ref: v1.3.1
#            path: libltc
      - run: dir
#        - run: dir libltc
      - run: dir C:\msys64
  build-libltc:
    name: Windows libltc Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: tc2artnet
      - run: sudo apt update && sudo apt install -y mingw-w64
      - run: chmod +x tc2artnet/scripts/* && tc2artnet/scripts/build-libltc-windows.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libltc_win
          path: libltc_win
